### ISSUE TITLE
Standalone app works, but Matrix widget doesn't... proxy problems?

### ISSUE THREAD

**Issue by JoKeyser** [Johni0702/mumble-web#37]
I've got the page to run behind my apache2 proxy at https://example.com/mumble/, see https://github.com/Johni0702/mumble-web/issues/18#issuecomment-427609760.
(Note also my Synapse is proxied through apache2: `ProxyPass /_matrix http://localhost:8008/_matrix`.)
When try to add this as a custom Matrix widget, I can see the interface properly in Riot Desktop, but it doesn't connect (neither to my mumble on the same server, nor the demo):

![view_from_riotapp](https://user-images.githubusercontent.com/8722846/46581190-767fd780-ca34-11e8-829e-f0d2aed65c61.png)

When I try to view the widget from the https://riot.im/app/ client, it does not even show the interface, it just stays blank.

I'm suspecting an issue with my proxying. 

```
[TIMESTAMP] [gnutls:error] [pid 3426] [remote 127.0.0.1:8008] ssl_engine_set: mod_proxy requested TLS proxy, but not enabled for (null)
[TIMESTAMP] [gnutls:error] [pid 4082] [remote 127.0.0.1:64737] ssl_engine_set: mod_proxy requested TLS proxy, but not enabled for (null)
```

Before delving into details, @Johni0702 could you confirm that the app/any settings should allow the use of the widget from the same server, both proxied through a web-server? I mean, does it work for your `nginx` settings?

Any tips what to test are very welcome.

**Comment by SISheogorath** [comment]
Mhm, I just did a quick test with my instance (mumble.madirc.net) and it seems to work.

Notice this is not the latest version of mumble-web I should get my fork back in sync. But in general it doesn't seem to be a matrix problem:

![image](https://user-images.githubusercontent.com/8719867/46581415-87cae300-ca38-11e8-842f-c56e4a8712f8.png)

**Comment by JoKeyser** [comment]
Thank you @SISheogorath, that helps a lot to narrow it down. Just to be sure we talk about similar settings, your Synapse is also on the same domain, also proxied through the same apache2 that you described at https://github.com/Johni0702/mumble-web/issues/18#issuecomment-337175632?

**Comment by SISheogorath** [comment]
Nope, I don't run an own synapse instance. I run on the public matrix.org instance and tried the embedding in the Riot Desktop client. But I don't expect it to be a problem related to the synpase reverse proxy, since the domains are independent at least in my case.

**Comment by JoKeyser** [comment]
Actually, the demo at https://voice.johni0702.de doesn't work either on my own synapse, I should have tested that earlier.
@SISheogorath , most interestingly your widget at https://mumble.madirc.net *does* work on my own Synapse, even when connecting to my mumble server!
So I think this is really a problem with the current code rather than my setup.

(Less importantly, to further exclude possible problems, I've replicated the problem with a) synapse and mumble-web running on different VirtualHosts and domains, and b) using `mod_ssl` instead of `mod_gnutls`. Neither makes a difference in the behavior; I see the widget in Riot Desktop, but connection to any server fails.)

**Comment by Johni0702** [comment]
Loads and connects fine on Riot Web (using Firefox) for me using the demo url and server.

For Riot Desktop I'm running into [this Chrome bug](https://bugs.chromium.org/p/chromium/issues/detail?id=31666) which fits with @SISheogorath's fork working in Riot Web since I've only recently (beafbe1) started using nested web workers. There seems to be a polyfill for Chrome to work around the issue, I've yet to try it though.
@JoKeyser are you by any chance using Riot Web via Chrome as well?

**Comment by JoKeyser** [comment]
@Johni0702 thanks for checking in so quickly. I'm puzzled that we see different things. Your hunch about different browser versions explains some of the confusion. To take my own server out of the equation, I've made a fresh account on matrix.org and re-tested both widget URLs with Firefox Quantum 62.0.3 (64-bit) and Chrome 61.0.3163.100 (Official Build) (64-bit), all on riot.im (on ArchLinux).

Using Firefox, I actually can't even see the widget dialog box to create new widgets, so probably failing to render the widgets has nothing to do with anything. For both widgets, I just see `Sorry, this content is not embeddable in Matrix`.

Using Chrome and @SISheogorath 's widget (https://mumble.madirc.net) in connects fine to itself, but fails to connect to the demo (voice.johni0702.de): `Connection error: [object Event]`.
Using Chrome and the demo widget (https://voice.johni0702.de), I cannot connect to either; it just halts after messages like `Connecting to server mumble.madirc.net`.

**Comment by Johni0702** [comment]
That looks like an issue with Modular (Riot's default integrations manager). Try embedding some random site (e.g. [this](https://matrix.org/docs/spec/client_server/r0.4.0.html) one). If the problem persists, try asking in [#riot:matrix.org](https://matrix.to/#/#riot:matrix.org) (not sure if there's a more specialized room for Modular, they'll probably send you there if one exists).

**Comment by JoKeyser** [comment]
@Johni0702 thank you, I will wait until bf731c7 is deployed on the demo site for further tests, and then open another issue if needed.

Note, embedding https://matrix.org/docs/spec/client_server/r0.4.0.html seems to work fine in my Riot Desktop does also evoke the Error `Error while parsing the 'allow' attribute: 'microphone;', 'camera;', 'encrypted-media;' are invalid feature names.`, but not the later `Uncaught ReferenceError: Worker is not defined` (see above).

**Comment by Johni0702** [comment]
> Note, embedding https://matrix.org/docs/spec/client_server/r0.4.0.html seems to work fine in my Riot Desktop.

Yes, yes, the chrome (which is what Riot Desktop uses) issue should be fixed with bf731c7. I was referring to this with my last reply:
> I've re-tried with Firefox running without any extensions (Help > Restart with Add-ons Disabled), and it still fails. The dev console reports `Content is not embeddable Forbidden - Invalid Scalar access token`, maybe that screenshot sheds some light

`Scalar` is the old name of `Modular` (the Integrations Manager) iirc, which is why I suspect it to be an issue with that (and therefore all widgets / not mumble-web specific).

**Comment by JoKeyser** [comment]
Ah sorry about my confusion, that makes sense. Indeed, even https://matrix.org/docs/spec/client_server/r0.4.0.html does not work in my Firefox, so that's off the table.

Once bf731c7 hits the demo server, I'd like to try with my Riot Desktop. In case there is still an issue, I'll open another one here; this one is quite polluted with many erroneous routes :). Thanks again.

**Comment by JoKeyser** [comment]
Epilogue: Success! I've pulled  bf731c7 into my own server (mumble-web and synapse proxied through apache2 with mod_gnutls), and now the widget works in Riot Desktop.
